services:
  viser-pet-next:
    container_name: viser-pet-next
    restart: always
    image: node:20.10.0
    ports:
      - 4023:3000
    environment:
      - PORT=3000

    volumes:
      - ./:/usr/src/viser-pet-next
    working_dir: /usr/src/viser-pet-next

    networks:
      - client-network

    # FOR PRODUCTION
    command: bash -c "yarn install && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge
# nestar-next:  localhost:4000 <=> container:3000
# nestar-api:   localhost:4001 <=> container:3007
# nestar-batch: localhost:4002 <=> container:3008
